### ISSUE TITLE
《CSS: The Missing Manual》阅读笔记

### ISSUE THREAD

**Issue by perry2008084** [perry2008084/Blog#12]
#### Chapter1 HTML and CSS
- div - a block, a line break before it and after it; span - inline, part of a paragraph.
- layout - don't use html tag to control style
- (validate web page)[http://validator.w3.org]
- Tips to guide your way
  - use headings to indicate the relative importance of text.
  - "p" for paragraph
  - "ul" for unordered lists
  - "ol" for numbered  lists
  - "dl" for definition or description
  - "q" for quote or <block-quote>
  - "cite" for title, article or website, <address> for contact infomation
    #### Chapter2 Creating Styles and Style Sheets
- Selector: elements on a page to style

``` CSS
Selector { Property: value; Property: value; }

p {
    color: red;
    font-size: 1.5em;
}
```
- force reload: Ctrl+F5 or Ctrl+R
- internal style sheets
- external sytle sheets

``` CSS
<link rel="stylesheet" href="css/styles.css">
```
#### Chapter3 Selectors: Identifying What to Style
- Type Selectors: styling  HTML Tags
- Class Selectors: Pinpoint Control
- One Tag, Multiple Classes
- ID Selectors: Specific Page Elements

``` CSS
#id name{
    background: #CC0000;
}
```
- Styling Groups  of  Tags
  Construct Group Selectors
  Universal Selector(Asterisk)
